branch-defaults:
  master:
    environment: Principle12Backend-env
deploy:
  artifact: target/com.codurance.principle12.backend-0.0.1-SNAPSHOT.jar
global:
  application_name: Principle12-Backend
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2/3.0.1
  default_region: eu-west-1
  sc: git
